[package]
name = "vn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vndb-api = { path = "../../" }
dotenvy = "0.15"
tokio = { version = "1", features = ["full", "macros"] }
